### ISSUE TITLE
memory leak issue in the match (bin)

### ISSUE THREAD

**Issue by gafoor52** [robwhess/opensift#10]
Hi,
I'm using match.c for matching two frames. I ran the executable with valgrind tool. I found 6 blocks are still reachable.
And the print is as follows:

==17724== Memcheck, a memory error detector
==17724== Copyright (C) 2002-2011, and GNU GPL'd, by Julian Seward et al.
==17724== Using Valgrind-3.7.0 and LibVEX; rerun with -h for copyright info
==17724== Command: ./bin/match /home/gaian/test_png_folder/thumb5.png /home/gaian/test_png_folder/thumb6.png
==17724== 
==17724== Conditional jump or move depends on uninitialised value(s)
==17724==    at 0x5B04DD8: inflateReset2 (in /lib/i386-linux-gnu/libz.so.1.2.3.4)
==17724==    by 0x5B04EC7: inflateInit2_ (in /lib/i386-linux-gnu/libz.so.1.2.3.4)
==17724== 
Finding features in /home/image1.png...
Finding features in /home/image2.png...
Building kd tree...
Found 2710 total matches
==17724== 
==17724== HEAP SUMMARY:
==17724==     in use at exit: 9,276 bytes in 6 blocks
==17724==   total heap usage: 807,627 allocs, 807,621 frees, 282,519,676 bytes allocated
==17724== 
==17724== 1,036 bytes in 1 blocks are still reachable in loss record 1 of 6
==17724==    at 0x402BE68: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==17724==    by 0x6FA0979: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F9F2FB: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FA1064: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F62B03: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x400EEAA: call_init (dl-init.c:85)
==17724==    by 0x400EF93: _dl_init (dl-init.c:134)
==17724==    by 0x400120E: ??? (in /lib/i386-linux-gnu/ld-2.15.so)
==17724== 
==17724== 1,036 bytes in 1 blocks are still reachable in loss record 2 of 6
==17724==    at 0x402BE68: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==17724==    by 0x6FA0979: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F9DDC4: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FA1080: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F62B03: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x400EEAA: call_init (dl-init.c:85)
==17724==    by 0x400EF93: _dl_init (dl-init.c:134)
==17724==    by 0x400120E: ??? (in /lib/i386-linux-gnu/ld-2.15.so)
==17724== 
==17724== 1,036 bytes in 1 blocks are still reachable in loss record 3 of 6
==17724==    at 0x402BE68: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==17724==    by 0x6FA0979: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FBCC34: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F8EF5A: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FA108A: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F62B03: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x400EEAA: call_init (dl-init.c:85)
==17724==    by 0x400EF93: _dl_init (dl-init.c:134)
==17724==    by 0x400120E: ??? (in /lib/i386-linux-gnu/ld-2.15.so)
==17724== 
==17724== 1,036 bytes in 1 blocks are still reachable in loss record 4 of 6
==17724==    at 0x402BE68: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==17724==    by 0x6FA0979: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FE1749: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F8EF32: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FA108A: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F62B03: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x400EEAA: call_init (dl-init.c:85)
==17724==    by 0x400EF93: _dl_init (dl-init.c:134)
==17724==    by 0x400120E: ??? (in /lib/i386-linux-gnu/ld-2.15.so)
==17724== 
==17724== 1,036 bytes in 1 blocks are still reachable in loss record 5 of 6
==17724==    at 0x402BE68: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==17724==    by 0x6FA0979: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FA4DA4: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6FA10AA: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x6F62B03: ??? (in /usr/lib/i386-linux-gnu/libpixman-1.so.0.30.2)
==17724==    by 0x400EEAA: call_init (dl-init.c:85)
==17724==    by 0x400EF93: _dl_init (dl-init.c:134)
==17724==    by 0x400120E: ??? (in /lib/i386-linux-gnu/ld-2.15.so)
==17724== 
==17724== 4,096 bytes in 1 blocks are still reachable in loss record 6 of 6
==17724==    at 0x402BE68: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==17724==    by 0x5C21AB7: libjpeg_general_init (in /usr/lib/i386-linux-gnu/libjpeg.so.8.0.2)
==17724==    by 0x400EEAA: call_init (dl-init.c:85)
==17724==    by 0x400EF93: _dl_init (dl-init.c:134)
==17724==    by 0x400120E: ??? (in /lib/i386-linux-gnu/ld-2.15.so)
==17724== 
==17724== LEAK SUMMARY:
==17724==    definitely lost: 0 bytes in 0 blocks
==17724==    indirectly lost: 0 bytes in 0 blocks
==17724==      possibly lost: 0 bytes in 0 blocks
==17724==    still reachable: 9,276 bytes in 6 blocks
==17724==         suppressed: 0 bytes in 0 blocks
==17724== 
==17724== For counts of detected and suppressed errors, rerun with: -v
==17724== Use --track-origins=yes to see where uninitialised values come from
==17724== ERROR SUMMARY: 2 errors from 1 contexts (suppressed: 0 from 0)

**Comment by robwhess** [comment]
Hi @gafoor52. Thanks for raising the issue. Based on your valgrind output, it looks like the leaks you're finding are in libpixman and libjpeg.

**Comment by gafoor52** [comment]
Thanks for the reply @robwhess, can you guess / say why may be this memory leak in that library?

**Comment by robwhess** [comment]
@gafoor52 you mean based on the valgrind results? If you scroll through and look at each of the reachable blocks in the valgrind report, it's reporting them to be in those libraries. I don't really have any idea what's going on in those libraries. You might want to file bug reports upstream with them.

I'm going to close this issue.
