### ISSUE TITLE
Please document whether this is compatible with Lowe's sift tool

### ISSUE THREAD

**Issue by mardy** [robwhess/opensift#15]
Hi!
  The [bundler](https://github.com/snavely/bundler_sfm) program includes a shell script to invoke Lowe's `sift` tool in order to extract features from `.pgm` images. The original tool has some limitations (it's especially limited on the image size, so it won't work on larger images) and it would be interesting to know if the `siftfeat` program included in this project is compatible with it -- that is, whether it accepts the same input and delivers the output in the same format.
If it's not compatible, but you are able to document what the difference are, I could contribute a small shell script that wraps `siftfeat` in a way that makes it compatible with the original `sift`.

**Comment by robwhess** [comment]
`siftfeat` produces the same format of output as Lowe's `sift` tool.  I haven't been maintaining this code because it's been incorporated into OpenCV since version 2.3, so I may or may not have time to update the docs.
