### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jodevak** [robwhess/opensift#21]
Is this patent licensed or free ?

**Comment by robwhess** [comment]
There are two separate issues here that you may be conflating: patenting and copyright. The SIFT algorithm itself is patented, and use of the algorithm is restricted by that patent. The copyright for this specific implementation of SIFT (i.e. the code itself) is governed by the BSD license. You are free to use the code under the terms of the license. However, it is your responsibility to abide by the terms of the patent on the SIFT algorithm, and I assume no responsibility for any way in which you violate that patent using this code. Please see the LICENSE file included in this repo for more details.
